### ISSUE TITLE
提取完特征点以后怎么进行配准

### ISSUE THREAD

**Issue by dzz416** [hakaboom/py_image_registration#10]
两幅图提取完特征点以后，如何利用仿射变换等映射手段将一幅图向另一幅图配准呢？

**Comment by hakaboom** [comment]
https://github.com/hakaboom/py_image_registration/blob/d374da654576727648eb2178c236860212a79311/image_registration/keypoint_matching/kaze.py#L318-L321
主要是这一段代码，具体的调用可以到文件里去看
